### ISSUE TITLE
New Display Image Tiles funny

### ISSUE THREAD

**Issue by jimpipe** [gpilab/core-nodes#1]
The awesome new tile feature in ImageDisplay, when fed 3D data, works like tile _used to_ work in Dimensions, i.e. the tiled dimension must be a perfect product of (# rows) and (# columns), so if e.g. the 3rd dimension is 13, you can only tile as 13x1 or 1x13.

It would be awesome if this functionality could be extended as done w/ the new Dimensions, so that only "tiled dimension" >= (# rows) and (# columns) is enforced, and residual data is set to zero - thus e.g. 13 objects could be tiled 5x3 or 4x4.

**Comment by aganders3** [comment]
I believe this is (finally) fixed by e5d60743. Please test it!
