### ISSUE TITLE
Matplotlib node compatibility issues

### ISSUE THREAD

**Issue by borupdaniel** [gpilab/core-nodes#11]
The matplotlib node is experiencing a few issues related to newer versions of Matplotlib. The issues I've noted so far:

- set_axis_bgcolor was deprecated in V2.0. This causes nothing to display. 
- The "hold" attribute was removed from the Figure class in V3.

 @grlee77 has written a fix for the first issue that I will cherry-pick and apply in the develop branch. The second issue should be fixable in a similar manner. Beyond that, rewriting the node for compatibility with V3.0 could be a larger project.

**Comment by aganders3** [comment]
While packaging I'm noticing that for some reason there is no Linux build of matplotlib 2 that is compatible with pyqt4. The newest it will let me install it seems is 1.5. Do you think the changes you've made here compatible with 1.5? If so I will add a preprocessor step to change the matplotlib versions to `>=1.5,<2` for linux and keep `>=2.1,<3` for mac.

**Comment by borupdaniel** [comment]
I think that should be fine — both fixes use a try-catch so that if the deprecated functions are available, they'll execute normally.
