### ISSUE TITLE
disk memory fills up on OSX

### ISSUE THREAD

**Issue by michaelschar** [gpilab/core-nodes#5]
Hi GpiLab gurus,

Lately I kept running out of disk memory. I found that the folder com.gpilab.GPI still had 126GB even after having closed all canvases.  I assume those files remained after a couple crashes I experienced last week. Deleting all files in that folder resolved the problem. Just thought this may be helpful for other users to know. Here is the hidden path where that folder is on my computer:
/private/var/folders/66/dw_7jnhd44jg_x1rhhhrfmwm0000gn/T/com.gpilab.GPI/

Thanks!
Mike

**Comment by nckz** [comment]
This "tmp" directory should also clear up on restart in both Linux and OSX.

**Comment by michaelschar** [comment]
Thanks Nick, turns out I wasn't able to empty the trash, and only restarting did the job in the end.

**Comment by michaelschar** [comment]
Thanks Nick, turns out I wasn't able to empty the trash, and only restarting did the job in the end.
