### ISSUE TITLE
NODE creation instruction?

### ISSUE THREAD

**Issue by Mazecreator** [gpilab/core-nodes#9]
Is there another place you have the instructions for creating NODES?

This link seems to be broken:
http://docs.gpilab.com/CoreNodes/

I am looking into the feasibility of using this tool for TensorFlow.

**Comment by nckz** [comment]
Hi Greg,

Can you tell me where you found that link? -Id like to fix it.

You can find info on writing nodes here:
http://docs.gpilab.com/en/develop/NodeDev/devguide.html

and you may need to setup a library directory with info from here:
http://docs.gpilab.com/en/develop/config.html

There is also a "new node" button in the main menu, that will write a node template to help you get started.

-Nick

**Comment by Mazecreator** [comment]
Thanks, I will check it out.  The link is on the top of the main "Code" page:
The core nodes are a collection of basic data manipulation and visualization algorithms. http://docs.gpilab.com/CoreNodes/

**Comment by rkrobison** [comment]
Changed the link at the top of the core-nodes repo Code main page.
